chore: upgrade dependencies for k8s 1.25
keikoproj/cluster-validator pull request #20
Opened 2023-09-27 23:26 UTC by sbadla1

chore: upgrade dependencies for k8s 1.25

2023-09-27 23:59 UTC, vgunapati approved these changes

2023-09-28 01:21 UTC, ZihanJiang96 approved these changes

2023-09-28 02:51 UTC, tekenstam approved these changes

2023-09-28 03:40 UTC, tekenstam requested changes
Please make the unit-test github action pass.

2023-09-28 10:28 UTC, tekenstam approved these changes

2023-09-28 10:29 UTC, merged